const fingerPrintRout = require("./Hr/FingerPrintRout");
const paymentHistoryRout = require("./paymentHistoryRout");
const brandRout = require("./Settings/Definition/brand.route");
const categoryRout = require("./categoryRout");
const companyInfoRoute = require("./Settings/Company/company.route");
const currencyRoute = require("./Settings/currence.route");
const discountRoute = require("./discountRoute");
const addressRout = require("./ecommerce/addressRout");
const cartRout = require("./ecommerce/cartRout");
const ecommerceOrderRouter = require("./ecommerce/ecommerceOrderRout");
const reviewRout = require("./ecommerce/reviewRout");
const wishlistRouter = require("./ecommerce/wishlistRout");
const employeeRoute = require("./employeeRoute");
const expenseCategoriesRoute = require("./Accounting/Expense/expensesCategoryRoute");
const invoiceHistoryRoute = require("./invoiceHistoryRoute");
const paymentTypes = require("./paymentTypesRoute");
const productMovementsRoute = require("./productMovementRoute");
const rawMaterialMovementRoute = require("./rawMatrialMovementRoute");
const productRout = require("./productRout");
const PurchaseInvoices = require("./Accounting/Purchase/purchaseInvoices.route");
const RefundPurchaseInvoices = require("./Accounting/Purchase/refundPurchaseInvoices.route");
const RoleDashboardRoute = require("./roleDashboardRoute");
const StockReconciliationRoute = require("./stockReconciliationRoute");
const taxRout = require("./Settings/Definition/tax.route");
const unitRout = require("./Settings/Definition/unit.route");
const authRoute = require("./authRoute");
const customarRoute = require("./customarRoute");
const supplierRoute = require("./supplierRoute");
const roleRoute = require("./roleRoute");
const stockRout = require("./stokRoute");
const footerRout = require("./ecommerce/footerRout");
const offersRouter = require("./offersRoute");
const paytrRouter = require("./ecommerce/paytrRoute");
const devicesRout = require("./maintenance/devicesRout");
const quotationRouter = require("./quotationRoute");
const E_userRoute = require("./ecommerce/E_usersRoutes");
const thirdPartyRoute = require("./ecommerce/thirdPartyAuthRoute");
const accountingTreeRout = require("./accountingTreeRoute");
const manitUserRout = require("./maintenance/maintenanceUserRoute");
const manitCaseRout = require("./maintenance/manitencesCaseRoute");
const shippingCompaniesRoute = require("./shippingCompaniesRoute");
const ecommercePaymentMethodRoute = require("./ecommerce/ecommercePaymentMethodRoute");
const purchaseRequestRouter = require("./purchaseRequestRoute");
const journalEntryRoute = require("./Accounting/JournalEntries/JournalEntries.route");
const unTracedproductLogRout = require("./unTracedproductLogRout");
const TagRoute = require("./Settings/Definition/tag.route");
const SalesPointRout = require("./salesPointRoute");
const linkPanelRoute = require("./LinkPanelRout");
const staffRout = require("./Hr/staffRout");
const questionsRoute = require("./ecommerce/productQuestionsRoute");
const ecommerceSettingsRoute = require("./ecommerce/ecommerceSettingsRoute");
const hepsiJetRouter = require("./ecommerce/hepsiJetRoute");
const noticesRouter = require("./noticesRoute");
const salaryHistoryRoute = require("./Hr/salaryHistoryRoute");
const batchRoute = require("./resturant_management/batchRoute");
const rawMaterialRoute = require("./resturant_management/rawMaterialRoute");
const recipeRoute = require("./resturant_management/recipeRoute");
const manufactorProductRoute = require("./resturant_management/manufatorProductRoute");
const menuCategoryRout = require("./resturant_management/menuCategoryRoute");
const positionsRout = require("./Hr/positionsRoute");
const efaturaRoute = require("./efatura/efaturaRoute");
const assetCategoryRoute = require("./assetCategoryRoute");
const finalAsset = require("./finalAssetRoute");
const assetCardRoute = require("./assetCardRoute");
const investorRoute = require("./investment/investorRoute");
const investmentCompaniesRoute = require("./investment/investmentCompaniesRoute");
const investorSharesRoute = require("./investment/investorSharesRoute");
const reconciliationRoute = require("./reconciliationRoute");
const closingReportRoute = require("./reports/closingReportRoute");
const budgetRoute = require("./reports/budgetRoute");
const menuOrderRoute = require("./resturant_management/menuOrderRoute");
const tableRoute = require("./resturant_management/tablesRoute");
const hrAuthRout = require("./Hr/hrAuthRoute");
const groupsRoute = require("./Hr/groupsRoute");
const locationRoute = require("./Hr/locationRoute");
const jobRoute = require("./Hr/jobManagementRoute");
const paymentRouteV2 = require("./Accounting/CurrentAssets/payment.route");
const incomeStatementRoute = require("./reports/incomeStatementRoute");
const balanceSheetsStatementRoute = require("./reports/balanceSheetsStatementRoute");
const cashFlowRoute = require("./reports/cashFlowRoute");
const ShortageRoute = require("./ShortageRoute");
const branchRoute = require("./Hr/branchesRoute");
const departmentRoute = require("./Hr/departmentRoute");
const jobGradesRoute = require("./Hr/jobGradesRoute");
const currencyLogRoute = require("./currencyLogRoute");
const sharePurchaseRequestRoute = require("./investment/sharePurchaseRequestRoute");
const productBatchRoute = require("./productBatchRoute");
const filesRoute = require("./Hr/filesRoute");
const staffFilesRoute = require("./Hr/staffFilesRoute");
const leavesRoute = require("./Hr/Leaves/leavesRoute");
const ReconciliationRoute = require("./Stocks/reconciliation/reconciliationRoute");
const leaveRequestRoutes = require("./Hr/Leaves/leaveRequestRoutes");
const leavesPolicyRoute = require("./Hr/Leaves/leavesPolicyRoute");
const leaveLogsRoute = require("./Hr/Leaves/leaveLogsRoute");
const overtimeTypesRoute = require("./Hr/Overtime/overtimeTypeRoute");
const overtimePolicyRoute = require("./Hr/Overtime/overtimePolicyRoute");
const overtimeRequestRoute = require("./Hr/Overtime/overtimeRequestRoute");
const overtimeLogsRoute = require("./Hr/Overtime/overtimeLogsRoute");
const advanceLogsRoute = require("./Hr/Advance/advanceLogsRoute");
const advancePolicyRoute = require("./Hr/Advance/advancePolicyRoute");
const advanceRequestRoute = require("./Hr/Advance/advanceRequestRoute");
const advanceTypesRoute = require("./Hr/Advance/advanceTypesRoute");
const approvalFlowRoute = require("./Hr/approvalFlowRoute");
const manufacturingRoute = require("./manufacturing/manufacturingRoute");
const noticesRoute = require("./Hr/notificationRoute");
const deductionPolicyRoute = require("./Hr/deductionPolicyRoute");
const deductionTypesRoute = require("./Hr/deductionTypesRoute");
const payrollPeriodRoute = require("./Hr/payrollPeriodRoute");
const payrollGroupsRoute = require("./Hr/payrollGroupsRoute");
const tasksRoute = require("./Tasks/task.route");
const subtasksRoute = require("./Tasks/subTask.route");
const commentRoute = require("./Tasks/comment.route");
const attachmentRoute = require("./Tasks/attachment.route");
const ExpenseInvoices = require("./Accounting/Expense/expenseInvoices.route");
const SalesInvoices = require("./Accounting/Sales/salesInvoice.route");
const RefundSalesInvoices = require("./Accounting/Sales/refundSalesIvoice.route");
const FundAndBank = require("./Accounting/CurrentAssets/fundAndBank.route");
const FundTransfer = require("./Accounting/CurrentAssets/fundTransfer.route");
const BatchLedger = require("./Stocks/Batch/BatchLedger.route");
const actionExecutionRoute = require("./Hr/actionExecutionRoute");
const violationLogRoute = require("./Hr/violationLogRoute");
const WorkspaceRoute = require("./Tasks/workspace.routes");
const FolderRoute = require("./Tasks/folder.routes");
const ListRoute = require("./Tasks/list.routes");
const timeTrackingRoute = require("./Tasks/timeTracking.route");
const subTaskRoute = require("./Tasks/subTask.route");
const userRoute = require("./Settings/user.route");
const PosReceiptRoute = require("./Pos/pos.receipt.route");
const PosReceiptRefundRoute = require("./Pos/pos.receipt_refund.route");
const roleRouter = require("./Settings/role.route");
const DashboardStatsRoute = require("./dashboardStatsRoute");
const permissionsRouter = require("./Settings/permissions.route");

const mountRoutes = (app) => {
  app.use("/api/dashboard-stats", DashboardStatsRoute);
  app.use("/api/product", productRout);
  app.use("/api/v1/brand", brandRout);
  app.use("/api/v1/permissions", permissionsRouter);
  app.use("/api/category", categoryRout);
  app.use("/api/customars", customarRoute);
  app.use("/api/suppliers", supplierRoute);
  app.use("/api/roledashboard", RoleDashboardRoute);
  app.use("/api/v1/roles", roleRouter);
  app.use("/api/employee", employeeRoute);
  app.use("/api/discount", discountRoute);
  app.use("/api/v1/unit", unitRout);
  app.use("/api/v1/tax", taxRout);
  app.use("/api/paymenttype", paymentTypes);
  app.use("/api/v1/users", userRoute);
  app.use("/api/v1/journal", journalEntryRoute);

  app.use("/api/v1/tag", TagRoute);
  app.use("/api/auth", authRoute);
  app.use("/api/v1/sales-invoices", SalesInvoices);
  app.use("/api/v1/refund-sales-invoices", RefundSalesInvoices);
  app.use("/api/v1/currency", currencyRoute);
  app.use("/api/v1/currencylog", currencyLogRoute);
  app.use("/api/v1/fund-bank", FundAndBank);
  app.use("/api/v1/fund-transfer", FundTransfer);
  app.use("/api/expenses", ExpenseInvoices);
  app.use("/api/purchaseInvoices", PurchaseInvoices);
  app.use("/api/refund-purchaseInvoices", RefundPurchaseInvoices);
  app.use("/api/expenseCategories", expenseCategoriesRoute);
  app.use("/api/v1/companyinfo", companyInfoRoute);
  app.use("/api/companyinfo", companyInfoRoute);
  app.use("/api/stockreconciliation", StockReconciliationRoute);
  app.use("/api/stockreconciliation-v1", ReconciliationRoute);
  app.use("/api/v1/receipt-pos", PosReceiptRoute);
  app.use("/api/v1/pos-receipt-Refund", PosReceiptRefundRoute);

  app.use("/api/productmovements", productMovementsRoute);
  app.use("/api/invoicehistory", invoiceHistoryRoute);
  app.use("/api/v2/payment", paymentRouteV2);
  app.use("/api/payment-history", paymentHistoryRout);
  app.use("/api/stock", stockRout);
  app.use("/api/offers", offersRouter);
  app.use("/api/quotation", quotationRouter);
  app.use("/api/accounting-tree", accountingTreeRout);
  app.use("/api/reconciliation", reconciliationRoute);
  app.use("/api/purchaserequest", purchaseRequestRouter);
  app.use("/api/shippingCompany", shippingCompaniesRoute);
  app.use("/api/untracedproductlog", unTracedproductLogRout);
  app.use("/api/salespoint", SalesPointRout);
  app.use("/api/linkpanel", linkPanelRoute);
  app.use("/api/notices", noticesRouter);
  app.use("/api/assetcategory", assetCategoryRoute);
  app.use("/api/finalasset", finalAsset);
  app.use("/api/assetcard", assetCardRoute);

  app.use("/api/shortage", ShortageRoute);
  app.use("/api/v1/product-batches", productBatchRoute);
  app.use("/api/v1/batch-ledger", BatchLedger);

  //Ecommerce routes
  app.use("/api/users", E_userRoute);
  app.use("/api/cart", cartRout);
  app.use("/api/wishlist", wishlistRouter);
  app.use("/api/addresses", addressRout);
  app.use("/api/ecommerce-order-router", ecommerceOrderRouter);
  app.use("/api/review", reviewRout);
  app.use("/api/questions", questionsRoute);
  app.use("/api/ecommerceSettings", ecommerceSettingsRoute);
  app.use("/api/footer", footerRout);
  app.use("/api/thirdPartyAuth", thirdPartyRoute);
  app.use("/api/ecommercePaymentMethods", ecommercePaymentMethodRoute);

  //HepsiJet
  app.use("/api/hepsijet", hepsiJetRouter);

  //E-Fatura
  app.use("/api/efatura", efaturaRoute);

  //Hr
  app.use("/api/staff", staffRout);
  app.use("/api/finger-print", fingerPrintRout);
  app.use("/api/salary-history", salaryHistoryRoute);
  app.use("/api/positions", positionsRout);
  app.use("/api/hrauth", hrAuthRout);
  app.use("/api/groups", groupsRoute);
  app.use("/api/locations", locationRoute);
  app.use("/api/jobs", jobRoute);
  app.use("/api/branch", branchRoute);
  app.use("/api/department", departmentRoute);
  app.use("/api/job-grades", jobGradesRoute);
  app.use("/api/files", filesRoute);
  app.use("/api/staff-files", staffFilesRoute);
  app.use("/api/leaves", leavesRoute);
  app.use("/api/leaves-policy", leavesPolicyRoute);
  app.use("/api/leave-request", leaveRequestRoutes);
  app.use("/api/leave-logs", leaveLogsRoute);
  app.use("/api/overtime-types", overtimeTypesRoute);
  app.use("/api/overtime-policy", overtimePolicyRoute);
  app.use("/api/overtime-request", overtimeRequestRoute);
  app.use("/api/overtime-logs", overtimeLogsRoute);
  app.use("/api/advance-logs", advanceLogsRoute);
  app.use("/api/advance-policy", advancePolicyRoute);
  app.use("/api/advance-request", advanceRequestRoute);
  app.use("/api/advance-types", advanceTypesRoute);
  app.use("/api/approval-flow", approvalFlowRoute);
  app.use("/api/notification", noticesRoute);
  app.use("/api/deduction-policy", deductionPolicyRoute);
  app.use("/api/deduction-types", deductionTypesRoute);
  app.use("/api/payroll-periods", payrollPeriodRoute);
  app.use("/api/payroll-groups", payrollGroupsRoute);

  app.use("/api/action-execution", actionExecutionRoute);
  app.use("/api/violation-logs", violationLogRoute);

  //task
  app.use("/api/workspace", WorkspaceRoute);
  app.use("/api/workspaces/:workspaceId/folders", FolderRoute);
  app.use("/api/workspaces/:workspaceId/folders/:folderId/lists", ListRoute);
  app.use("/api/lists/:listId/tasks", tasksRoute);
  app.use("/api/tasks/:taskId/subtasks", subTaskRoute);
  app.use("/api/comments", commentRoute);
  app.use("/api/attachments", attachmentRoute);
  app.use("/api/time-tracking", timeTrackingRoute);
  //Payment
  app.use("/api", paytrRouter);

  //Maintenance
  app.use("/api/device", devicesRout);
  app.use("/api/manituser", manitUserRout);
  app.use("/api/manitcase", manitCaseRout);

  //resturant_management
  app.use("/api/batch", batchRoute);
  app.use("/api/rawMaterial", rawMaterialRoute);
  app.use("/api/recipe", recipeRoute);
  app.use("/api/manufactorProduct", manufactorProductRoute);
  app.use("/api/menu-category", menuCategoryRout);
  app.use("/api/menu-order", menuOrderRoute);
  app.use("/api/table", tableRoute);
  app.use("/api/rawMaterialMovement", rawMaterialMovementRoute);

  //Investment
  app.use("/api/investor", investorRoute);
  app.use("/api/investmentCompanies", investmentCompaniesRoute);
  app.use("/api/investorShares", investorSharesRoute);
  app.use("/api/sharePurchaseRequest", sharePurchaseRequestRoute);

  //Report
  app.use("/api/closingreports", closingReportRoute);
  app.use("/api/budget", budgetRoute);
  app.use("/api/v1/income-statement", incomeStatementRoute);
  app.use("/api/v1/balance-sheet-statement", balanceSheetsStatementRoute);
  app.use("/api/v1/cash-flow", cashFlowRoute);
  //Manufacturing
  app.use("/api/manufacturing", manufacturingRoute);
};
module.exports = mountRoutes;
