const mongoose = require("mongoose");

const manitencesCase = new mongoose.Schema(
  {
    userId: { type: mongoose.Schema.ObjectId, ref: "manitUser" },
    deviceId: { type: mongoose.Schema.ObjectId, ref: "Device" },
    admin: String,
    userNotes: String,
    deviceProblem: String,
    deviceStatus: String,
    employeeDesc: String,
    expectedAmount: String,
    amountDue: { type: Number, default: 0 },
    partsCurrency: {
      id: { type: String },
      name: { type: String },
      symbol: { type: String },
      exchangeRate: { type: Number, default: 1 },
    },
    explanition: String,
    manitencesStatus: String,
    paymentStatus: { type: String, enum: ["paid", "unpaid"] },
    backpack: { type: Boolean, default: false },
    charger: { type: Boolean, default: false },
    cable: { type: Boolean, default: false },
    deliveryDate: String,
    deviceReceptionDate: String,
    problemType: String,
    caseStatus: String,
    customerCalling: [
      { connect: String, date: String, user: String, _id: false },
    ],
    caseCounter: String,
    piecesAndCost: [
      {
        type: { type: String, default: "product" },
        id: String,
        qr: String,
        name: String,
        category: String,
        orginalBuyingPrice: Number,
        profitRatio: Number,
        convertedBuyingPrice: Number,
        sellingPrice: Number,
        unit: String,
        tax: {
          _id: String,
          tax: Number,
          salesAccountTax: String,
          name: String,
        },
        taxValue: Number,
        stock: {
          _id: String,
          stock: { type: String },
          stockQuantity: Number,
        },
        soldQuantity: Number,
        totalWithoutTax: Number,
        total: Number,
        note: String,
        exchangeRate: Number,
        discountType: String,
        discountPercentege: Number,
        discountAmount: Number,
        discount: Number,
        showNote: Boolean,
        showDiscount: Boolean,
        buyingpriceMainCurrence: Number,
        _id: false,
      },
    ],
    technicalDesc: String,
    counter: String,
    companyId: {
      type: String,
      required: true,
      index: true,
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model("manitencesCase", manitencesCase);
