const mongoose = require("mongoose");

/* --------------------------------------------------------------------
   Calendar Rule SubSchema
-------------------------------------------------------------------- */
const calendarRuleSchema = new mongoose.Schema(
  {
    title: { type: String, required: true },
    year: { type: Number, required: true, index: true },

    patternType: {
      type: String,
      enum: [
        "SINGLE_DATE",
        "DATE_RANGE",
        "RECURRING_WEEKLY",
        "RECURRING_MONTHLY",
      ],
      required: true,
    },

    effectType: {
      type: String,
      enum: [
        "FULL_DAY_OFF",
        "PARTIAL_OFF",
        "CUSTOM_HOURS",
        "FORCE_WORKING",
      ],
      required: true,
    },

    startDate: { type: String }, // YYYY-MM-DD
    endDate: { type: String },   // YYYY-MM-DD

    startTime: { type: String }, // HH:mm
    endTime: { type: String },   // HH:mm

    daysOfWeek: [{ type: String }],
    dayOfMonth: { type: Number },
    repeatEvery: { type: Number, default: 1 },

    isAutoGenerated: { type: Boolean, default: false },
  },
  { _id: false }
);

/* --------------------------------------------------------------------
   Groups Schema
-------------------------------------------------------------------- */
const groupsSchema = new mongoose.Schema(
  {
    // --------------------------------------------------------------------
    // 1) General Info
    // --------------------------------------------------------------------
    groupName: { type: String, required: true },
    latinName: { type: String },
    description: { type: String },

    companyId: {
      type: String,
      required: true,
      index: true,
    },

    locationId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Location",
      default: null,
    },

    // --------------------------------------------------------------------
    // 2) Attendance
    // --------------------------------------------------------------------
    attendanceType: {
      type: String,
      enum: ["fixed", "flexible", "remote"],
      required: true,
    },

    offDays: [{ type: String }],

    // ---------- FIXED ----------
    fixedAttendance: {
      startTime: { type: String },
      endTime: { type: String },
      breakFrom: { type: String },
      breakTo: { type: String },
      earlyIn: { type: Number, default: 0 },
      earlyOut: { type: Number, default: 0 },
      overtime: { type: Number, default: 0 },
    },

    // ---------- FLEXIBLE ----------
    flexibleAttendance: {
      requiredHoursPerDay: { type: Number },
    },

    // ---------- REMOTE ----------
    remoteAttendance: {
      requiredHoursPerDay: { type: Number },
    },

    // --------------------------------------------------------------------
    // 3) Calendar Rules
    // --------------------------------------------------------------------
    calendarRules: [calendarRuleSchema],
  },
  { timestamps: true }
);

module.exports = mongoose.model("Groups", groupsSchema);
